% create workspace helper functions used in furuta_grey



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% DEFINE PHYSICAL PARAMETERS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% define free and fixed parameters
% these are the starting values
m1 = 35.27e-3;
m2 = 44.73e-3;
L1 = 192.16e-3;
L2 = 243.66e-3;
Jaddl = 0.1; % need to account for the moment of inertia of the encoder assembly
b1 = 0.5;
b2 = 4.59e-4;
Ke = 0.0918 * (60/2/pi);
Km = 1.5 * Ke;

% leave center of mass at the center of each arm
l1 = L1 / 2;
l2 = L2 / 2;

% the following are well characterized
Lm = 1.6e-3 ;
Rm = 1.47; 

%%% calculate values from the free parameters
% calculate moment of inertia of rod about COM
J1 = 1/12 * m1 * L1^2;
J2 = 1/12 * m2 * L2^2;

% these inertias are as defined in the paper [1]
J1hatv = J1 + m1*l1^2;
J2hatv = J2 + m2*l2^2;
J0hatv = J1hatv + m2*L1^2 + Jaddl ;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% DEFINE **NONLINEAR** PENDULUM DYNAMICS 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Describe nonlinear simplified dynamics symbolically
% NOTE difference from [1]: setting "disturbance torque" tau_2 = 0
syms theta_1 theta_1_dot ... rotor arm angle
     theta_2 theta_2_dot ... pendulum arm angle
     J_0_hat ... moment of intertia (MOI) experience by motor when pendulum in suspended equilib. pos.
     J_1_hat J_2_hat ... rotor and pendulum MOIs
     m_1 m_2 ... rotor and pendulum masses
     L_1 L_2 ... length of rotor and pendulum arms
     l_1 l_2 ... distance from pivot to rotor/pendulum masse
     b_1 b_2 ... rotor and pendulum damping coefficients
     tau_1   ... torque from motor
     tau_2 ...disturbance torque (just set this to zero)
     g % gravitational constant

theta_1_ddot = ( ...
              -J_2_hat*b_1                                           * theta_1_dot ...
             + m_2*L_1*l_2*cos(theta_2)*b_2                          * theta_2_dot ...
             - J_2_hat^2*sin(2*theta_2)                              * theta_1_dot*theta_2_dot ...
             - (1/2)*J_2_hat*m_2*L_1*l_2*cos(theta_2)*sin(2*theta_2) * theta_1_dot^2 ...
             + J_2_hat*m_2*L_1*l_2*sin(theta_2)                      * theta_2_dot^2 ...
             + J_2_hat                                               * tau_1 ...
             - m_2*L_1*l_2*(cos(theta_2))                            * tau_2 ...
             + (1/2)*m_2^2*l_2^2*L_1*sin(2*theta_2)                  * g ...
             )  ...
             / ( J_0_hat*J_2_hat + J_2_hat^2*sin(theta_2)^2 - m_2^2*L_1^2*l_2^2*cos(theta_2)^2 );


theta_2_ddot = ( ...
               m_2*L_1*l_2*cos(theta_2)*b_1                                      * theta_1_dot ...
             - b_2*(J_0_hat+J_2_hat*sin(theta_2)^2)                              * theta_2_dot ...
             + m_2*L_1*l_2*J_2_hat*cos(theta_2)*sin(2*theta_2)                   * theta_1_dot*theta_2_dot ...
             - (1/2)*sin(2*theta_2)*(J_0_hat*J_2_hat + J_2_hat^2*sin(theta_2)^2) * theta_1_dot^2 ...
             - (1/2)*m_2^2*L_1^2*l_2^2*sin(2*theta_2)                            * theta_2_dot^2 ...
             - m_2*L_1*l_2*cos(theta_2)                                          * tau_1 ...
             + ( J_0_hat + J_2_hat*sin(theta_2)^2 )                              * tau_2 ...
             - m_2*l_2*sin(theta_2)*(J_0_hat + J_2_hat*sin(theta_2)^2)           * g ...
             )  ...
             / ( J_0_hat*J_2_hat + J_2_hat^2*sin(theta_2)^2 - m_2^2*L_1^2*l_2^2*cos(theta_2)^2 );

subs_array = [ ...
              % theta_1      0
              % theta_1_dot  0
              % theta_2      0
              % theta_2_dot  0
              % J_0_hat      J0hatv
              % J_1_hat      J1hatv
              % J_2_hat      J2hatv
              % m_1          m1
              % m_2          m2
              % L_1          L1
              % L_2          L2
              % l_1          l1
              % l_2          l2
              % b_1          b1
              % b_2          b2
              % tau_1        0
              tau_2        0       % neglect disturbance torque
              g            9.81 
             ];

% substitute constant values
theta_1_ddot_slk = subs( ...
    theta_1_ddot, subs_array(:,1), subs_array(:,2) );
theta_2_ddot_slk = subs( ...
    theta_2_ddot, subs_array(:,1), subs_array(:,2) );

% create helper functions
matlabFunction( ...
    theta_1_ddot_slk, ...
    'Vars', [ ...
        theta_1, theta_1_dot, ...
        theta_2, theta_2_dot, ...
        tau_1, ...
        J_0_hat, J_1_hat, J_2_hat, ...
        m_1, m_2, ...
        L_1, L_2, ...
        l_1, l_2, ...
        b_1, b_2 ...
    ], ...
    'File', 'theta_1_ddot_func' ...
);

matlabFunction( ...
    theta_2_ddot_slk, ...
    'Vars', [ ...
        theta_1, theta_1_dot, ...
        theta_2, theta_2_dot, ...
        tau_1, ...
        J_0_hat, J_1_hat, J_2_hat, ...
        m_1, m_2, ...
        L_1, L_2, ...
        l_1, l_2, ...
        b_1, b_2 ...
    ], ...
    'File', 'theta_2_ddot_func' ...
);
% theta_1_ddot_func = matlabFunction( theta_1_ddot_slk, 'Vars', ...
%     [ theta_1, theta_1_dot, theta_2, theta_2_dot, tau_1 J_0_hat J_1_hat J_2_hat m_1 m_2 L_1 L_2 l_1 l_2 b_1 b_2] );
% 
% theta_2_ddot_func = matlabFunction( theta_2_ddot_slk, 'Vars', ...
%     [ theta_1, theta_1_dot, theta_2, theta_2_dot, tau_1 J_0_hat J_1_hat J_2_hat m_1 m_2 L_1 L_2 l_1 l_2 b_1 b_2] );
% 
