function theta_1_ddot_slk = theta_1_ddot_func(theta_1,theta_1_dot,theta_2,theta_2_dot,tau_1,J_0_hat,J_1_hat,J_2_hat,m_1,m_2,L_1,L_2,l_1,l_2,b_1,b_2)
%THETA_1_DDOT_FUNC
%    THETA_1_DDOT_SLK = THETA_1_DDOT_FUNC(THETA_1,THETA_1_DOT,THETA_2,THETA_2_DOT,TAU_1,J_0_hat,J_1_hat,J_2_hat,M_1,M_2,L_1,L_2,l_1,l_2,B_1,B_2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-May-2026 22:36:29

t2 = cos(theta_2);
t3 = sin(theta_2);
t4 = J_2_hat.^2;
t5 = l_2.^2;
t6 = m_2.^2;
t7 = theta_2.*2.0;
t8 = sin(t7);
theta_1_ddot_slk = (J_2_hat.*tau_1-J_2_hat.*b_1.*theta_1_dot+L_1.*t5.*t6.*t8.*(9.81e+2./2.0e+2)-t4.*t8.*theta_1_dot.*theta_2_dot+J_2_hat.*L_1.*l_2.*m_2.*t3.*theta_2_dot.^2+L_1.*b_2.*l_2.*m_2.*t2.*theta_2_dot-(J_2_hat.*L_1.*l_2.*m_2.*t2.*t8.*theta_1_dot.^2)./2.0)./(t3.^2.*t4+J_0_hat.*J_2_hat-L_1.^2.*t2.^2.*t5.*t6);
end
