function theta_2_ddot_slk = theta_2_ddot_func(theta_1,theta_1_dot,theta_2,theta_2_dot,tau_1,J_0_hat,J_1_hat,J_2_hat,m_1,m_2,L_1,L_2,l_1,l_2,b_1,b_2)
%THETA_2_DDOT_FUNC
%    THETA_2_DDOT_SLK = THETA_2_DDOT_FUNC(THETA_1,THETA_1_DOT,THETA_2,THETA_2_DOT,TAU_1,J_0_hat,J_1_hat,J_2_hat,M_1,M_2,L_1,L_2,l_1,l_2,B_1,B_2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-May-2026 22:36:30

t2 = cos(theta_2);
t3 = sin(theta_2);
t4 = J_2_hat.^2;
t5 = L_1.^2;
t6 = l_2.^2;
t7 = m_2.^2;
t8 = theta_2.*2.0;
t9 = J_0_hat.*J_2_hat;
t10 = sin(t8);
t11 = t3.^2;
t12 = J_2_hat.*t11;
t13 = t4.*t11;
t14 = J_0_hat+t12;
theta_2_ddot_slk = -(b_2.*t14.*theta_2_dot+(t10.*theta_1_dot.^2.*(t9+t13))./2.0+l_2.*m_2.*t3.*t14.*(9.81e+2./1.0e+2)+(t5.*t6.*t7.*t10.*theta_2_dot.^2)./2.0+L_1.*l_2.*m_2.*t2.*tau_1-L_1.*b_1.*l_2.*m_2.*t2.*theta_1_dot-J_2_hat.*L_1.*l_2.*m_2.*t2.*t10.*theta_1_dot.*theta_2_dot)./(t9+t13-t2.^2.*t5.*t6.*t7);
end
